name: estimate
on:
  workflow_dispatch:
jobs:
  estimate_models:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install -r resources/requirements.txt
      - name: Estimate models
        run: python src/estimate_models.py
