name: load
on:
  workflow_dispatch:
jobs:
  load_data:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download file
        run: curl -o reviews.csv https://raw.githubusercontent.com/manthanpatel98/Restaurant-Review-Sentiment-Analysis/master/Restaurant%20reviews.csv
      - name: Load database
        run: python src/load_dataset.py reviews.csv

  data_preparation:
    runs-on: self-hosted
    needs: load_data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Preprocessing data
        run: python src/data_preparation.py
