name: train
on:
  workflow_dispatch:
jobs:
  train_models:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Models train
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python src/train_models.py
      - name: Commit changes of version
        uses: EndBug/add-and-commit@v9.1.1
        with:
            default_author: github_actions
            message: 'Commit changes of version'

  additional_train_models:
    needs: train_models
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Additional train
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python src/additional_train_models.py
      - name: Commit changes of version
        uses: EndBug/add-and-commit@v9.1.1
        with:
            default_author: github_actions
            message: 'Commit changes of version'

